export { Hero } from './Hero'
export { About } from './About'
export { Services } from './Services'
export { Skills } from './Skills'
export { Projects } from './Projects'
export { Contact } from './Contact'
